name: Build and Push Docker Image

on:
  push:
    branches: ['*']

permissions:
  contents: write

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get tag
        id: get_tag
        run: |
          latest_tag=$(git tag --sort=-v:refname | grep -E '^v[0-9]+\.[0-9]+\.[0-9]+$' | head -n 1)
          echo "Latest tag: $latest_tag"
          if [ -z "$latest_tag" ]; then
            latest_tag="v0.0.0"
          fi
          echo "tag=$latest_tag" >> $GITHUB_OUTPUT

      - name: Bump patch version
        id: bump
        run: |
          old=${{ steps.get_tag.outputs.tag }}
          IFS='.' read -r -a parts <<< "${old#v}"
          major=${parts[0]}
          minor=${parts[1]}
          patch=${parts[2]}
          new_patch=$((patch + 1))
          new_tag="v${major}.${minor}.${new_patch}"
          echo "New tag: $new_tag"
          echo "new_tag=$new_tag" >> $GITHUB_OUTPUT

      - name: Create new git tag and push
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git tag ${{ steps.bump.outputs.new_tag }}
          git push origin ${{ steps.bump.outputs.new_tag }}

#      - name: Set up Docker Buildx
#        uses: docker/setup-buildx-action@v3
      - name: Set up QEMU for emulation
        uses: docker/setup-qemu-action@v2

      - name: Build Docker image
        run: |
            docker build -t springk8s .

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            simonnguyen/springk8s:lastest,
            simonnguyen/springk8s:${{ steps.bump.outputs.new_tag }}
